### ISSUE TITLE
dotnvim specific configuration?

### ISSUE THREAD

**Issue by cknoerle** [dontpanic92/aerovim#2]
Is it possible to check if dotnvim is running? Something like `if exists ('g:GuiLoaded')` ?
I would like to apply a couple of dotnvim specific settings like font etc.

I found dotnvim honors `:set guifont`.
Is there any specific settings? I could not find any documentation.

Thanks
Chris

**Comment by dontpanic92** [comment]
Actually dotnvim didn't have any specific configurations. I just added a global variable `g:gui_dotnvim` to indicate dotnvim is running, please have a try.

`guifont` is the only one of the neovim [options](https://neovim.io/doc/user/options.html) that dotnvim has implemented... If you need more, please let me know.

Also added a [wiki page](https://github.com/dontpanic92/dotnvim/wiki/dotnvim-specific-configurations) for anyone who is interested in the same issue.
