### ISSUE TITLE
dotnvim在不同模式下光标的形状不会改变

### ISSUE THREAD

**Issue by avriltank** [dontpanic92/aerovim#4]
能够像gvim一样的话，插入模式下光标形状变成一条细竖线，按esc退回到普通模式又变成粗块光标形状的话，就相当完美了！无意间发现这个项目，真的很棒！这个是windows下nvim最好最快的gui了，测过neovim-qt，goneovim，fnvim，neovide(rust)！点个赞，希望作者大大能把这个更新到neovim gui的release projetct里边，让更多人知道

**Comment by dontpanic92** [comment]
v0.5 版本应该已经可以支持不同的光标形状了，可以试一下

**Comment by dontpanic92** [comment]
感谢建议哈，加到了 Related Projects 里😏

**Comment by avriltank** [comment]
终于等到这个功能了，谢谢
