### ISSUE TITLE
打开coc-explorer,会闪退

### ISSUE THREAD

**Issue by BlueFLs** [dontpanic92/aerovim#5]
做的很nice,不过打开coc-explorer,简单进行操作，尤其是按退格键回到上一级目录的时候，会出现闪退现象。
电脑操作系统：win10 20H2
neovim:0.44
dotnvim:0.5

**Comment by dontpanic92** [comment]
似乎是因为发给 nvim 的 `backspace` 没有映射为 `<Bs>` 而是直接用了 `\b`，我这边的现象是在 coc explorer 里面 backspace 完全不起作用
更新了一版添加了 backspace 的映射，我这边已经可以正常返回上一级了，可以试一下看看

**Comment by BlueFLs** [comment]
试了下，应该是好了，很棒
